### ISSUE TITLE
Node Red Error

### ISSUE THREAD

**Issue by mtoko** [damoclark/node-red-contrib-cec#1]
Hi
Great contribution
I have followed the instructions but when I use any of the nodes on a Raspberry Pi Node Red crashes and consistently tries to restart. The problem seems to be the config of the adapter.
Error code is
5 Sep 11:02:46 - [red] Uncaught Exception:
5 Sep 11:02:46 - Error: spawn cec-client ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.

Any ideas?

**Comment by mtoko** [comment]
Hi 

Update
installed the Pulse Eight utils and now Node Red does not crash (sorry)
I have tried the example flow but debug indicates no serial port

**Comment by damoclark** [comment]
cec-client will attempt to search for a serial port if you do not specify one.  On a Raspberry Pi, my experience is that it locates it without issue.  If you are using different hardware, then you will need to determine the serial port name and provide that to the cec config node.  

Also, check that your cec adapter is supported by PulseEight.  

Let me know how it goes.

D.

**Comment by mtoko** [comment]
Thanks for the reply
I have started with a completely new Raspbian on a Pi and then followed all the steps again. Node Red crashed once on start and then it worked fine.
Good work great documentation!

**Comment by damoclark** [comment]
No worries.  Hope you find it useful.

I might need to wrap the spawn in a try block and provide a more helpful error advising to install cec-client.  It's easily missed in the instruction.

By the way, the serial port for a raspberry pi is "RPI" if you wanted to be explicit.

Have fun with it.

Damo.
