### ISSUE TITLE
'damoclark/cec-monitor' is not in the npm registry

### ISSUE THREAD

**Issue by tyts100** [damoclark/node-red-contrib-cec#2]
Hi,

I try to install node-red-contrib-cec on Raspbian installed on my new Raspbery Pi 3 from the scratch. Node-RED and npm are installed. But I get the follows as a result:
--------------------------------->
pi@raspberrypi:~ $ cd .node-red/
pi@raspberrypi:~/.node-red $ npm install --save @senzil/cec-monitor
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
 
> deasync@0.1.10 install /home/pi/.node-red/node_modules/@senzil/cec-monitor/node_modules/deasync-promise/node_modules/deasync
> node ./build.js

make: Entering directory '/home/pi/.node-red/node_modules/@senzil/cec-monitor/node_modules/deasync-promise/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
  SOLINK_MODULE(target) Release/obj.target/deasync.node
  COPY Release/deasync.node
make: Leaving directory '/home/pi/.node-red/node_modules/@senzil/cec-monitor/node_modules/deasync-promise/node_modules/deasync/build'
Installed in `/home/pi/.node-red/node_modules/@senzil/cec-monitor/node_modules/deasync-promise/node_modules/deasync/bin/linux-arm-node-4/deasync.node`
@senzil/cec-monitor@2.0.0-release.79 node_modules/@senzil/cec-monitor
├── death@1.1.0
├── deasync-promise@1.0.1 (deasync@0.1.10)
└── event-stream@3.3.4 (pause-stream@0.0.11, stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.7, map-stream@0.1.0, through@2.3.8, split@0.3.3)
pi@raspberrypi:~/.node-red $ sudo apt-get update && sudo apt-get install cec-utils
Hit:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Hit:2 http://archive.raspbian.org/raspbian stretch InRelease
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done                 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cec-utils is already the newest version (4.0.2.3~stretch).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
pi@raspberrypi:~/.node-red $ npm install node-red-contrib-cec
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'damoclark/cec-monitor' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'node-red-contrib-cec'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-cec"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
-------------->

Where I'm wrong? Any ideas?

Best regards,
tyts100

**Comment by damoclark** [comment]
Hi Tyts100,

The problem is that you didn't specify the package name for the install:

```bash
pi@raspberrypi:~ $ cd .node-red/
pi@raspberrypi:~/.node-red $ npm install --save
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
```

You need to type:
```bash
pi@raspberrypi:~ $ cd .node-red/
pi@raspberrypi:~/.node-red $ npm install --save node-red-contrib-cec
```

D.

**Comment by tyts100** [comment]
Hi,

Thanks for your prompt feedback. Unfortunately, the same result.
---
pi@raspberrypi:~/.node-red $ npm install --save node-red-contrib-cec
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'damoclark/cec-monitor' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'node-red-contrib-cec'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "node-red-contrib-cec"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0
---

BR,
tyts100

**Comment by damoclark** [comment]
You are using a version of npm that is too old.

```
npm ERR! npm -v 1.4.21
```

You need to use version 3 or higher due to the namespaced package cec-monitor.  

You can attempt to update to a newer version of npm with:

```bash
$ sudo npm -g install npm
```

D.

**Comment by tyts100** [comment]
Hi,

Thank you. Now I have
pi@raspberrypi:~ $ npm -v
5.5.1

And node-red-contrib-cec has been installed succesfully.

BR,
tyts100
