### ISSUE TITLE
Won't install on stretch 

### ISSUE THREAD

**Issue by marksmanaz** [damoclark/node-red-contrib-cec#4]
Can't install from pallet or npm command. Tried to copy files to .node-red folder but nodes don't show.

**Comment by damoclark** [comment]
Hey @marksmanaz 

Unfortunately I don't have capacity at the moment due to work commitments to investigate any issues with this module.  

Will happily accept PR for any fixes to issues in the meantime however.  

Damo.

**Comment by marksmanaz** [comment]
I found the issue with install I had a old version of NPM I updated and now working.

Thank you

⁣Sent from BlueMail ​
